import { CheckCircleIcon, EditIcon, Home, InfoIcon, ReceiptIcon, SearchIcon } from "lucide-react";
import { ClipboardCheck } from "lucide-react";
import { SideBarMenuItemType } from "../../store/store";
import {
  DashboardIcon,
  AccountCircleIcon,
  GroupIcon,
  MonetizationOnIcon,
  ShowChartIcon,
  CreditCardIcon,
  MailOutlineIcon,
  PersonIcon,
  VerifiedUserIcon,
  LockIcon,
  PeopleIcon,
  AccountTreeIcon,
  PersonAddIcon,
  TrendingUpIcon,
  PaymentsIcon,
  EventIcon,
  BuildIcon,
} from "../Icons";
import {
  AccountBalance,
  Assignment,
  AssignmentOutlined,
  Cancel,
  Assessment as AssessmentIcon,
  Description as DescriptionIcon,
  AttachMoney as AttachMoneyIcon,
  FactCheck as FactCheckIcon,
  BusinessCenter as BusinessCenterIcon,
  AccountBalanceWallet as AccountBalanceWalletIcon,
  Book as BookIcon,
  Payment as PaymentIcon,
  ListAlt as ListAltIcon,
  Delete as DeleteIcon,
  Report as ReportIcon,
  PieChart as PieChartIcon,
  TaskAlt as TaskAltIcon,
  Savings as SavingsIcon,
  EventNote as EventNoteIcon,
  History as HistoryIcon,
  Autorenew as AutorenewIcon,
  Domain as DomainIcon,
  AddCircle as AddCircleIcon,
  RemoveCircle as RemoveCircleIcon,
  Update as UpdateIcon,
  LocationOn as LocationOnIcon,
  AccessTime as AccessTimeIcon,
  Undo as UndoIcon,
  Publish as PublishIcon,
  Schedule as ScheduleIcon,
  MoneyOff as MoneyOffIcon,
  Print as PrintIcon,
  Percent as PercentIcon,
  Calculate as CalculateIcon,
  Visibility as VisibilityIcon,
  CurrencyRupee as CurrencyRupeeIcon,
  CompareArrows as CompareArrowsIcon,
  Portrait as PortraitIcon
} from "@mui/icons-material";

export const UserSideBarMenuItems: SideBarMenuItemType[] = [
  {
    name: "Dashboard",
    icon: <DashboardIcon />,
    path: "/user/dashboard",
    isExpandable: false,
  },
  {
    name: "Account Info",
    icon: <AccountCircleIcon />,
    isExpandable: true,
    subItems: [
      { name: "Profile", path: "/user/account/profile", icon: <PersonIcon /> },
      { name: "KYC", path: "/user/account/kyc", icon: <VerifiedUserIcon /> },
      {
        name: "Change Password",
        path: "/user/account/change-password",
        icon: <LockIcon />,
      },
    ],
  },
  {
    name: "Team",
    icon: <GroupIcon />,
    isExpandable: true,
    subItems: [
      { name: "Direct", path: "/user/team/direct", icon: <PeopleIcon /> },
      { name: "Team", path: "/user/team", icon: <GroupIcon /> },
      { name: "Tree", path: "/user/team/tree", icon: <AccountTreeIcon /> },
      {
        name: "New Register",
        path: "/user/team/new-register",
        icon: <PersonAddIcon />,
      },
    ],
  },
  {
    name: "Earnings",
    icon: <MonetizationOnIcon />,
    isExpandable: true,
    subItems: [
      {
        name: "Level Benefits",
        path: "/user/earnings/level-benefits",
        icon: <TrendingUpIcon />,
      },
      {
        name: "Daily Payout",
        path: "/user/earnings/daily-payout",
        icon: <PaymentsIcon />,
      },
    ],
  },
 {
    name: "Transactions",
    icon: <ShowChartIcon />,
    isExpandable: true,
    subItems: [
      {
        name: "Wallet",
        path: "/user/transactions",
        icon: <CreditCardIcon />,
      },
      {
        name: "Loan",
        path: "/user/loantransactions",
        icon: <AccountBalance />,
      },
    ],
  },
  {
    name: "Wallet Balance",
    icon: <CreditCardIcon />,
    path: "/user/wallet",
    isExpandable: false,
  },
  {
    name: "Mail Box",
    icon: <MailOutlineIcon />,
    path: "/user/mailbox",
    isExpandable: false,
  },
];

export const AdminSideBarMenuItems: SideBarMenuItemType[] = [
  {
    name: "Home",
    icon: <Home />,
    path: "/master/index",
    isExpandable: false,
  },
  {
    name: "Master",
    icon: <BuildIcon />,
    isExpandable: true,
    subItems: [
      { name: "Admin Setting", path: "/master/view_mainconfig", icon: <DashboardIcon /> },
      { name: "State Master", path: "/master/view_state", icon: <AccountTreeIcon /> },
      { name: "City Master", path: "/master/view_city", icon: <AccountTreeIcon /> },
      { name: "Branch Master", path: "/master/view_branch_master", icon: <GroupIcon /> },
      { name: "Rank Name Master", path: "/master/view_rank_master", icon: <TrendingUpIcon /> },
      { name: "Rank Wise Comission Master", path: "/closing/closing_master", icon: <TrendingUpIcon /> },
      { name: "Plan Master", path: "/plan_master/view_sub_plan_type_master", icon: <AccountTreeIcon /> },
      { name: "Share Master", path: "/master/share", icon: <TrendingUpIcon /> },
      { name: "Member Fee Master", path: "/master/member-fee", icon: <PaymentsIcon /> },
      { name: "Advisor Fee Master", path: "/master/advisor-fee", icon: <PaymentsIcon /> },
      { name: "Proof Master", path: "/master/proof", icon: <VerifiedUserIcon /> },
      { name: "Company Bank Master", path: "/master/company-bank", icon: <CreditCardIcon /> },
      { name: "Set Back Date", path: "/master/set-back-date", icon: <EventIcon /> },
      { name: "Bank Master", path: "/master/bank", icon: <CreditCardIcon /> },
      { name: "Message", path: "/master/message", icon: <MailOutlineIcon /> },
      { name: "Fine Offer", path: "/master/fine-offer", icon: <MonetizationOnIcon /> },
      { name: "Reverse Passbook", path: "/master/reverse-passbook", icon: <CreditCardIcon /> },
      { name: "Message To Member", path: "/master/message-to-member", icon: <MailOutlineIcon /> },
      { name: "Closing Month Master", path: "/master/closing-month", icon: <EventIcon /> },
      { name: "Closing Master(Comission charge)", path: "/master/closing-comission-charge", icon: <PaymentsIcon /> },
      { name: "Closing Master(Collections charge)", path: "/master/closing-collection-charge", icon: <PaymentsIcon /> },
    ],
  },
  {
    name: "Assign Menu",
    icon: <Assignment />,
    isExpandable: true,
    subItems: [
      { name: "Assign Menu Branch", path: "/assign-menu/branch", icon: <GroupIcon /> },
      { name: "Assign Menu Advisor", path: "/assign-menu/advisor", icon: <PersonIcon /> },
      { name: "Assign Menu Member", path: "/assign-menu/member", icon: <PersonIcon /> },
      { name: "Assign Menu Employee", path: "/assign-menu/employee", icon: <PersonIcon /> },
      { name: "View Assign Menu Report", path: "/assign-menu/report", icon: <AssignmentOutlined /> }
    ],
  },
  {
    name: "Update Master",
    icon: <EditIcon />,
    isExpandable: true,
    subItems: [
      { name: "Update Nominee Plan", path: "/update-master/nominee-plan", icon: <AssignmentOutlined /> },
      { name: "Update Introducer", path: "/update-master/introducer", icon: <AssignmentOutlined /> },
      { name: "Update Collector", path: "/update-master/collector", icon: <AssignmentOutlined /> },
      { name: "Update Admin Menu", path: "/update-master/admin-menu", icon: <EditIcon /> },
      { name: "Update Branch Menu", path: "/update-master/branch-menu", icon: <EditIcon /> },
      { name: "Update Fine", path: "/update-master/fine", icon: <MonetizationOnIcon /> },
      { name: "Update Member ID", path: "/update-master/member-id", icon: <PersonIcon /> },
      { name: "Update Advisor ID", path: "/update-master/advisor-id", icon: <PersonIcon /> },
      { name: "Update Plan ID", path: "/update-master/plan-id", icon: <AssignmentOutlined /> },
    ],
  },
  {
    name: "Member",
    icon: <PersonIcon />,
    isExpandable: true,
    subItems: [
      { name: "Member Registration", path: "/member/registration", icon: <PersonAddIcon /> },
      { name: "Member KYC", path: "/member/kyc", icon: <VerifiedUserIcon /> },
      { name: "Edit Member Detail", path: "/member/edit-detail", icon: <EditIcon /> },
      { name: "Search Members", path: "/member/search", icon: <SearchIcon /> },
      { name: "Member Ledger", path: "/member/ledger", icon: <ReceiptIcon /> },
      { name: "Activate Member", path: "/member/activate", icon: <CheckCircleIcon /> },
      { name: "DE-Activate Member", path: "/member/deactivate", icon: <Cancel /> },
      { name: "Share", path: "/member/share", icon: <TrendingUpIcon /> },
      { name: "Member Login Detail", path: "/member/login-detail", icon: <InfoIcon /> },
    ],
  },
  {
    name: "Advisor",
    icon: <PersonIcon />,
    isExpandable: true,
    subItems: [
      { name: "Advisor Registration", path: "/advisor/registration", icon: <PersonAddIcon /> },
      { name: "Search Advisors", path: "/advisor/search", icon: <SearchIcon /> },
      { name: "View Advisors Team", path: "/advisor/team", icon: <GroupIcon /> },
      { name: "Advisors Upline Detail", path: "/advisor/upline-detail", icon: <TrendingUpIcon /> },
      { name: "Advisor Rank Update", path: "/advisor/rank-update", icon: <TrendingUpIcon /> },
      { name: "Advisor Branch Update", path: "/advisor/branch-update", icon: <GroupIcon /> },
      { name: "Advisor Login Detail", path: "/advisor/login-detail", icon: <InfoIcon /> },
      { name: "Tree View", path: "/advisor/tree-view", icon: <AccountTreeIcon /> },
      { name: "Advisor's Self & Team Bus.", path: "/advisor/self-team-business", icon: <BusinessCenterIcon /> },
    ],
  },
  
  {
    name: "Fixed Deposit A/C",
    icon: <AccountBalanceWalletIcon />,
    isExpandable: true,
    subItems: [
      { name: "FD Accounts Detail", path: "/fixed-deposit/accounts-detail", icon: <ReceiptIcon /> },
      { name: "FD Maturity List", path: "/fixed-deposit/maturity-list", icon: <EventNoteIcon /> },
      { name: "FD Maturity Paid Report", path: "/fixed-deposit/maturity-paid-report", icon: <AssessmentIcon /> },
    ],
  },
  {
    name: "Recurring Deposit A/C",
    icon: <SavingsIcon />,
    isExpandable: true,
    subItems: [
      { name: "RD Accounts Detail", path: "/recurring-deposit/accounts-detail", icon: <ReceiptIcon /> },
      { name: "RD Renewal Pay", path: "/recurring-deposit/renewal-pay", icon: <MonetizationOnIcon /> },
      { name: "DUE RD Renewal List", path: "/recurring-deposit/due-renewal-list", icon: <EventNoteIcon /> },
      { name: "RD Renewal Detail", path: "/recurring-deposit/renewal-detail", icon: <EventNoteIcon /> },
      { name: "RD Maturity List", path: "/recurring-deposit/maturity-list", icon: <EventNoteIcon /> },
      { name: "RD Maturity Paid Report", path: "/recurring-deposit/maturity-paid-report", icon: <AssessmentIcon /> },
      { name: "RD Complete Plan Report", path: "/recurring-deposit/complete-plan-report", icon: <ReportIcon /> },
      { name: "Upcoming Collection", path: "/recurring-deposit/upcoming-collection", icon: <ScheduleIcon /> },
    ],
  },
  {
    name: "Daily Deposit A/C",
    icon: <AccountBalanceWalletIcon />,
    isExpandable: true,
    subItems: [
      { name: "DD Accounts Detail", path: "/daily-deposit/accounts-detail", icon: <ReceiptIcon /> },
      { name: "DD Renewal", path: "/daily-deposit/renewal", icon: <HistoryIcon /> },
      { name: "DUE Renewal Report", path: "/daily-deposit/due-renewal-report", icon: <ReportIcon /> },
      { name: "Daily Deposit Report", path: "/daily-deposit/report", icon: <AssessmentIcon /> },
      { name: "Daily Renewal Detail", path: "/daily-deposit/renewal-detail", icon: <HistoryIcon /> },
      { name: "DD Maturity List", path: "/daily-deposit/maturity-list", icon: <EventNoteIcon /> },
      { name: "DD Maturity Paid Report", path: "/daily-deposit/maturity-paid-report", icon: <AssessmentIcon /> },
      { name: "DD Complete Plan Report", path: "/daily-deposit/complete-plan-report", icon: <ReportIcon /> },
      { name: "Upcoming Collection", path: "/daily-deposit/upcoming-collection", icon: <ScheduleIcon /> },
    ],
  },
  {
    name: "MIS A/C",
    icon: <AutorenewIcon />,
    isExpandable: true,
    subItems: [
      { name: "MIS Account Detail", path: "/mis/account-detail", icon: <ReceiptIcon /> },
      { name: "MIS Pay", path: "/mis/pay", icon: <PaymentIcon /> },
      { name: "MIS Paid Report", path: "/mis/paid-report", icon: <AssessmentIcon /> },
      { name: "MIS Maturity List", path: "/mis/maturity-list", icon: <EventNoteIcon /> },
      { name: "MIS Maturity Paid Report", path: "/mis/maturity-paid-report", icon: <AssessmentIcon /> },
      { name: "MIS Complete Plan Report", path: "/mis/complete-plan-report", icon: <ReportIcon /> },
    ],
  },
  {
    name: "Saving Accounts",
    icon: <SavingsIcon />,
    isExpandable: true,
    subItems: [
      { name: "Detail & Deposit", path: "/saving-accounts/detail-deposit", icon: <ReceiptIcon /> },
      { name: "Withdrawal", path: "/saving-accounts/withdrawal", icon: <MoneyOffIcon /> },
      { name: "Transaction Ledger", path: "/saving-accounts/transaction-ledger", icon: <BookIcon /> },
      { name: "Passbook Print", path: "/saving-accounts/passbook-print", icon: <PrintIcon /> },
      { name: "Saving Interest Master", path: "/saving-accounts/interest-master", icon: <PercentIcon /> },
      { name: "Generate Saving Interest", path: "/saving-accounts/generate-interest", icon: <CalculateIcon /> },
      { name: "View Saving Interest", path: "/saving-accounts/view-interest", icon: <VisibilityIcon /> },
    ],
  },
  {
    name: "Miscellaneous Reports",
    icon: <AssessmentIcon />,
    isExpandable: true,
    subItems: [
      { name: "All Plan Report", path: "/misc-reports/all-plan", icon: <DescriptionIcon /> },
      { name: "Spot Commission Report", path: "/misc-reports/spot-commission", icon: <AttachMoneyIcon /> },
      { name: "Collector Wise Collection Report", path: "/misc-reports/collector-collection", icon: <PeopleIcon /> },
      { name: "Spot Commission Paid Report", path: "/misc-reports/spot-commission-paid", icon: <MonetizationOnIcon /> },
      { name: "Advisor Wise TDS Report", path: "/misc-reports/advisor-tds", icon: <FactCheckIcon /> },
      { name: "Advisor ORC Statement", path: "/misc-reports/advisor-orc", icon: <ReceiptIcon /> },
      { name: "Reverse Passbook", path: "/misc-reports/reverse-passbook", icon: <ReceiptIcon /> },
      { name: "Approve Branch Maturity", path: "/misc-reports/approve-branch-maturity", icon: <CheckCircleIcon /> },
      { name: "Approve Collector Collection", path: "/misc-reports/approve-collector-collection", icon: <CheckCircleIcon /> },
      { name: "All Collection Report(Approved)", path: "/misc-reports/all-collection-approved", icon: <FactCheckIcon /> },
      { name: "Advisor Business", path: "/misc-reports/advisor-business", icon: <BusinessCenterIcon /> },
      { name: "Associate Collection Report", path: "/misc-reports/associate-collection", icon: <GroupIcon /> },
      { name: "Branch Wise Collection Report", path: "/misc-reports/branch-collection", icon: <GroupIcon /> },
    ],
  },
  {
    name: "Transfer Amount",
    icon: <CurrencyRupeeIcon />,
    isExpandable: true,
    subItems: [
      { name: "Amount Transfer", path: "/transfer-amount/amount-transfer", icon: <CompareArrowsIcon /> },
      { name: "Approved Fund Transfer", path: "/transfer-amount/approved-fund-transfer", icon: <CheckCircleIcon /> },
      { name: "Branch Fund Transfer Report", path: "/transfer-amount/branch-fund-transfer-report", icon: <FactCheckIcon /> },
    ],
  },
  {
    name: "Accounts",
    icon: <AccountBalanceWalletIcon />,
    isExpandable: true,
    subItems: [
      { name: "Daybook", path: "/accounts/daybook", icon: <BookIcon /> },
      { name: "Payment Voucher", path: "/accounts/payment-voucher", icon: <PaymentIcon /> },
      { name: "Receive Voucher", path: "/accounts/receive-voucher", icon: <ReceiptIcon /> },
      { name: "Payment Voucher Report", path: "/accounts/payment-voucher-report", icon: <AssessmentIcon /> },
      { name: "Recived Voucher Report", path: "/accounts/received-voucher-report", icon: <AssessmentIcon /> },
      { name: "Accounts Ledger Head Wise", path: "/accounts/ledger-head-wise", icon: <ListAltIcon /> },
      { name: "TDS Reports", path: "/accounts/tds-reports", icon: <FactCheckIcon /> },
      { name: "Balance Sheet", path: "/accounts/balance-sheet", icon: <AccountBalanceWalletIcon /> },
      { name: "Trial Balance", path: "/accounts/trial-balance", icon: <AccountBalanceWalletIcon /> },
      { name: "Voucher Detail (Payment/Received)", path: "/accounts/voucher-detail", icon: <InfoIcon /> },
      { name: "Delete Voucher Entry", path: "/accounts/delete-voucher-entry", icon: <DeleteIcon /> },
      { name: "Deleted Voucher Report", path: "/accounts/deleted-voucher-report", icon: <ReportIcon /> },
      { name: "Update Ledger", path: "/accounts/update-ledger", icon: <EditIcon /> },
      { name: "Chart Of Account New", path: "/accounts/chart-of-account-new", icon: <PieChartIcon /> },
      { name: "Balance Sheet New", path: "/accounts/balance-sheet-new", icon: <AccountBalanceWalletIcon /> },
    ],
  },
  {
    name: "Bank",
    icon: <DomainIcon />,
    isExpandable: true,
    subItems: [
      { name: "Bank Daybook", path: "/bank/daybook", icon: <BookIcon /> },
      { name: "Bank Deposit", path: "/bank/deposit", icon: <AddCircleIcon /> },
      { name: "Bank Withdrawal", path: "/bank/withdrawal", icon: <RemoveCircleIcon /> },
      { name: "Bank Deposited Report", path: "/bank/deposited-report", icon: <AssessmentIcon /> },
      { name: "Bank Withdrawal Report", path: "/bank/withdrawal-report", icon: <AssessmentIcon /> },
      { name: "Cheque Status Update(Uncleared)", path: "/bank/cheque-status-update", icon: <UpdateIcon /> },
      { name: "Change Cheque Deposit Location", path: "/bank/change-cheque-location", icon: <LocationOnIcon /> },
      { name: "Cleared Cheque Report", path: "/bank/cleared-cheque-report", icon: <CheckCircleIcon /> },
      { name: "Uncleared Cheque Report", path: "/bank/uncleared-cheque-report", icon: <ReportIcon /> },
      { name: "Rejected Cheque Report", path: "/bank/rejected-cheque-report", icon: <Cancel /> },
    ],
  },
  {
    name: "Business Closing",
    icon: <AccessTimeIcon />,
    isExpandable: true,
    subItems: [
      { name: "Generate Closing", path: "/business-closing/generate-closing", icon: <BuildIcon /> },
      { name: "Check Statement", path: "/business-closing/check-statement", icon: <ReceiptIcon /> },
      { name: "Reverse Closing", path: "/business-closing/reverse-closing", icon: <UndoIcon /> },
      { name: "Publish Closing", path: "/business-closing/publish-closing", icon: <PublishIcon /> },
      { name: "Published Closing Report", path: "/business-closing/closing-report", icon: <AssessmentIcon /> },
      { name: "Closing Month Master", path: "/business-closing/month-master", icon: <EventNoteIcon /> },
      { name: "Closing Master(Comission charge)", path: "/business-closing/commission-charge", icon: <MonetizationOnIcon /> },
      { name: "Closing Master(Collection charge)", path: "/business-closing/collection-charge", icon: <MonetizationOnIcon /> },
    ],
  },
  {
    name: "Delete Master",
    icon: <DeleteIcon />,
    isExpandable: true,
    subItems: [
      { name: "Delete Ledger Entry", path: "/delete-master/ledger-entry", icon: <DeleteIcon /> },
      { name: "Delete Installment", path: "/delete-master/installment", icon: <DeleteIcon /> },
      { name: "Delete Plan", path: "/delete-master/plan", icon: <DeleteIcon /> },
      { name: "Delete Loan", path: "/delete-master/loan", icon: <DeleteIcon /> },
      { name: "Delete Loan Installment", path: "/delete-master/loan-installment", icon: <DeleteIcon /> },
    ],
  },
  {
    name: "HR",
    icon: <PortraitIcon />,
    path: "/hr",
    isExpandable: false,
  },
  {
    name: "Switch to Loan",
    icon: <CompareArrowsIcon />,
    path: "/switch-to-loan",
    isExpandable: false,
  },
  {
    name: "Employees Work Report",
    icon: <TaskAltIcon />,
    isExpandable: true,
    subItems: [
      { name: "Member Detail", path: "/employees-work-report/member-detail", icon: <PersonIcon /> },
      { name: "Plan Report", path: "/employees-work-report/plan-report", icon: <DescriptionIcon /> },
      { name: "Plan Installment Report", path: "/employees-work-report/plan-installment-report", icon: <ReceiptIcon /> },
      { name: "Saving Plan Report", path: "/employees-work-report/saving-plan-report", icon: <AssessmentIcon /> },
      { name: "Loan Report", path: "/employees-work-report/loan-report", icon: <DescriptionIcon /> },
      { name: "Loan Installment Report", path: "/employees-work-report/loan-installment-report", icon: <ReceiptIcon /> },
      { name: "Payment Voucher Report", path: "/employees-work-report/payment-voucher-report", icon: <AssessmentIcon /> },
      { name: "Receive Voucher Report", path: "/employees-work-report/receive-voucher-report", icon: <AssessmentIcon /> },
      { name: "View Payment Bank Report", path: "/employees-work-report/payment-bank-report", icon: <AccountBalanceWalletIcon /> },
      { name: "View Receive Bank Report", path: "/employees-work-report/receive-bank-report", icon: <AccountBalanceWalletIcon /> },
    ],
  },
  {
    name: "Special Plan A/C",
    icon: <SavingsIcon />,
    isExpandable: true,
    subItems: [
      { name: "New Special Account", path: "/special-plan/new-account", icon: <AddCircleIcon /> },
      { name: "Special Accounts Detail", path: "/special-plan/accounts-detail", icon: <ReceiptIcon /> },
      { name: "Special Renewal Pay", path: "/special-plan/renewal-pay", icon: <MonetizationOnIcon /> },
      { name: "Special Renewal Detail", path: "/special-plan/renewal-detail", icon: <HistoryIcon /> },
      { name: "Special Maturity List", path: "/special-plan/maturity-list", icon: <EventNoteIcon /> },
      { name: "Special Maturity Paid Report", path: "/special-plan/maturity-paid-report", icon: <AssessmentIcon /> },
      { name: "Special Complete Plan Report", path: "/special-plan/complete-plan-report", icon: <ReportIcon /> },
    ],
  },
  {
    name: "CA Report",
    icon: <DescriptionIcon />,
    isExpandable: true,
    subItems: [
      { name: "Plan Booking", path: "/ca-report/plan-booking", icon: <BookIcon /> },
      { name: "Plan Installment", path: "/ca-report/plan-installment", icon: <ReceiptIcon /> },
      { name: "Saving Booking", path: "/ca-report/saving-booking", icon: <BookIcon /> },
      { name: "Saving Transactions", path: "/ca-report/saving-transactions", icon: <ListAltIcon /> },
      { name: "Loan Booking", path: "/ca-report/loan-booking", icon: <BookIcon /> },
      { name: "Loan Installment", path: "/ca-report/loan-installment", icon: <ReceiptIcon /> },
      { name: "Voucher Payment Report", path: "/ca-report/voucher-payment-report", icon: <AssessmentIcon /> },
      { name: "Voucher Receive Report", path: "/ca-report/voucher-receive-report", icon: <AssessmentIcon /> },
      { name: "Plan Advance Amount Report", path: "/ca-report/plan-advance-amount-report", icon: <ReportIcon /> },
      { name: "Loan Advance Amount Report", path: "/ca-report/loan-advance-amount-report", icon: <ReportIcon /> },
    ],
  },
  {
    name: "Account Head Master",
    icon: <BuildIcon />,
    isExpandable: true,
    subItems: [
      { name: "Chart Of Account", path: "/account-head-master/chart-of-account", icon: <PieChartIcon /> },
      { name: "Edit Chart Of Account", path: "/account-head-master/edit-chart-of-account", icon: <EditIcon /> },
      { name: "Head Status", path: "/account-head-master/head-status", icon: <InfoIcon /> },
    ],
  }
];

export const AdviserSideBarMenuItems: SideBarMenuItemType[] = [
  {
    name: "Home",
    icon: <DashboardIcon />,
    path: "/admin/dashboard",
    isExpandable: false,
  },

  {
    name: "Plans",
    icon: <ClipboardCheck />,
    isExpandable: false,
    path: "/admin/plans"
  },

  {
    name: "Team",
    icon: <GroupIcon />,
    isExpandable: false,
    path: "/admin/team",
  },

  {
    name: "Loan",
    icon: <CreditCardIcon />,
    isExpandable: true,
    subItems: [
      { name: "Self Loan", path: "/admin/loan/self", icon: <CreditCardIcon /> },
      { name: "Advised Loan", path: "/admin/loan/advised", icon: <CreditCardIcon /> },
    ],
  },

  {
    name: "Payout",
    icon: <PaymentsIcon />,
    isExpandable: true,
    subItems: [
      { name: "Payout Report", path: "/admin/payout/report", icon: <PaymentsIcon /> },
    ],
  },

  {
    name: "Plan Recovery",
    icon: <TrendingUpIcon />,
    isExpandable: true,
    subItems: [
      { name: "Plan Recovery", path: "/admin/plan/recovery", icon: <TrendingUpIcon /> },
      { name: "Plan Recovery Report", path: "/admin/plan/recovery-report", icon: <ShowChartIcon /> },
    ],
  },

  {
    name: "Loan Recovery",
    icon: <MonetizationOnIcon />,
    isExpandable: true,
    subItems: [
      { name: "Loan Recovery", path: "/admin/loan/recovery", icon: <MonetizationOnIcon /> },
      { name: "Loan Recovery Report", path: "/admin/loan/recovery-report", icon: <ShowChartIcon /> },
    ],
  },
];

export const AgentSideBarMenuItems: SideBarMenuItemType[] = [
  {
    name: "Dashboard",
    icon: <DashboardIcon />,
    path: "/agent/dashboard",
    isExpandable: false,
  },
  {
    name: "Profile",
    icon: <AccountCircleIcon />,
    path: "/agent/profile",
    isExpandable: false,
  },
  {
    name: "Collections",
    icon: <ListAltIcon />,
    path: "/agent/collections",
    isExpandable: false,
  },
  {
    name: "Add New",
    icon: <AddCircleIcon />,
    path: "/agent/add-new",
    isExpandable: false,
  },
  {
    name: "Report",
    icon: <AssessmentIcon />,
    path: "/agent/report",
    isExpandable: false,
  },
  {
    name: "Logout",
    icon: <InfoIcon />,
    path: "/",
    isExpandable: false,
  },
];